name: changelog_widgets_fluent_ui
description: Flutter package to read 'CHANGELOG.md' file
  and display it in the app as a Fluent UI widget.
version: 1.0.2
homepage: https://github.com/DamianAldair/changelog_widgets_fluent_ui
repository: https://github.com/DamianAldair/changelog_widgets_fluent_ui

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  fluent_ui: ^4.9.1
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
